### ISSUE TITLE
FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by Adilrn** [laxmaniron/3D-Animation#1]
Thank you  for this repository, I have been trying for so long to animate an character with some 3D keypoints of human in Unity unsuccessfully. Your repository is  really helping. But I run into an issue when I copied your results in  the folder "my_code" in the assets folder. I get the following error: FormatException: Input string was not in a correct format.

![image](https://user-images.githubusercontent.com/65495424/103305429-1ee53200-49d9-11eb-8f54-fc83255c81f5.png)

I don't know if you still maintain this repo but could you please point me to what needs to be corrected?

**Comment by laxmaniron** [comment]
Fixed it
