### ISSUE TITLE
Confusion regarding the intermediate outputs in overall process

### ISSUE THREAD

**Issue by SID-SURANGE** [laxmaniron/3D-Animation#3]
Hi, I have recently started working into Pose estimation and Unity. The repository seems very interesting and I wanted to create the same things but due to non clarity in the intermediate inputs and output from each model I am stuck in between.

As per the instruction- 
1) Run AlphaPose and use the output in DeepSort. Should I use the **Alphapose-output.json** as input to DeepSort?

2) What specific output do I require from DeepSort ?

Can I possibly get some help or references in understanding the overall steps with outputs. 

Thanks

**Comment by laxmaniron** [comment]
Hi, Sorry for not updating the repo, now Alpha Pose can also do pose tracking , no need to use separate module for pose tracking, just use, alpha pose + it's inbuilt pose tracker. https://github.com/MVIG-SJTU/AlphaPose , Refer to this for  more info

**Comment by SID-SURANGE** [comment]
Thanks for the update @laxmaniron . I needed a small help in drawing the roadmap for my requirement. **_I have a video file as input(mostly exercise videos), I need to capture the motion of person in video and then apply it to 3d character in Unity_**. I feel the steps would be to 
1) Extract person's keypoints corresponding to each frame in video.
2) Convert those 2D keypoints to 3D.
3) Apply the same using c# script to a 3D Character in Unity and thus the character follows same motion as in the video input.

Please correct me in my steps if wrong. Also would using **_AlphaPose and 3d-pose-baseline_**, help me achieve this?

Thanks in Advance.
